### ISSUE TITLE
Scala.js 1.x / Scala 2.13

### ISSUE THREAD

**Issue by Sciss** [cibotech/evilplot#127]
Hello! Looks like a great project. Do you publish artifacts for Scala.js 1.x on Scala 2.13? https://github.com/cibotech/evilplot/pull/99 indicates that Scala 2.13 should be supported, but I can only see artefacts published for Scala.js 0.6: https://dl.bintray.com/cibotech/public/com/cibo/

**Comment by alexklibisz** [comment]
@Sciss We don't currently publish for sjs 1.x on 2.13. We haven't updated sjs in some time, but if you make a PR we can review/merge/release it.

**Comment by williamyaoh** [comment]
This should be resolved as of 0.9.0.
