### ISSUE TITLE
Bintray repositories are down

### ISSUE THREAD

**Issue by TimingAttck** [cibotech/evilplot#139]
I hope this is the right place to post this.

Everything you hosted on Bintray is not available since it is down.
https://dl.bintray.com/cibotech/public/com/cibo/evilplot_2.11/0.6.3/evilplot_2.11-0.6.3.jar

Can you maybe provide the jar files on github?

In particular I need evilplot_2.11-0.6.3.jar.

Thank you

**Comment by ahawkins318** [comment]
Hi, we switched our hosting to sonatype shortly after bintray announced their sunset. You will need to update your import: 
```
"io.github.cibotech" %% "evilplot" % "0.8.1"
```

**Comment by TimingAttck** [comment]
Hi, thank you for your response.

Are you also hosting on sonatype a version of evilplot for scala 2.11?

**Comment by ahawkins318** [comment]
No, we are not. Here are the available versions: https://search.maven.org/search?q=g:io.github.cibotech

**Comment by TimingAttck** [comment]
Oh too bad, since I am required (by the university) to use scala 2.11.
Thank you very much for your help tho.

**Comment by TimingAttck** [comment]
I got the jar I needed through the wayback machine.
Sorry, I should have checked there first.
