### ISSUE TITLE
Change artifact repository due the sunset of bintray

### ISSUE THREAD

**Issue by cric96** [cibotech/evilplot#140]
Hi,
I try to use evilplot in my project but when I try to add the dependency in my build.sbt, it returns `403 Forbidden`.
I think the problem here is that evilplot was hosted in bintray that is currently no more [up](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).
So, it is possible to move the packages into maven central?

**Comment by ahawkins318** [comment]
We migrated away from bintray some time ago, here is the updated dependency:
```
libraryDependencies += "io.github.cibotech" %% "evilplot" % "0.8.1"
```
