### ISSUE TITLE
please add Scala 2.11 cross build for interactive notebooks support

### ISSUE THREAD

**Issue by strobe** [cibotech/evilplot#23]
Much of scala based notebooks depends on Spark witch still based on 2.11, therefore 
users of all notebooks projects like:
  - Apache Zeppelin
  - Apache Toree
  - spark-notebook
  - jupyter-scala
currently can't use 'evilplot' for plotting.

**Comment by johndavidhahn** [comment]
I know its been quiet on this for a bit.  This is an item on our backlog, and if it was as simple as just re-enabling 2.11 it would be done.  Unfortunately we've introduced some 2.12 specific code (overloaded `apply` methods to be exact) and reverting requires a potentially breaking change to the API.

Long story short.  We are going to address this (we also plan on doing some work with EvilPlot and scala notebooks) we just haven't yet.  And no, we aren't just trying to wait until everyone else is on 2.12 :)

Thanks for your patience.
