### ISSUE TITLE
evilplot-math dependency for Scala 2.12 is absent

### ISSUE THREAD

**Issue by rrwright** [cibotech/evilplot#85]
`com.cibo:evilplot-math_2.12:0.6.1` seems to be a missing dependency. Consequently, [the getting starting docs](https://cibotech.github.io/evilplot/getting-started.html) are broken. That jar is available for scala 2.11, but not 2.12—even though other 2.12 resources are present - https://dl.bintray.com/cibotech/public/com/cibo/

**Comment by johndavidhahn** [comment]
Thanks for the heads up.  We'll likely be releasing a 0.6.2 soon, which might only fix this 0.6.1 artifact issue.

**Comment by johndavidhahn** [comment]
evilplot 0.6.2 has been deployed which fixes this artifact issue.
