### ISSUE TITLE
legend generation no longer working as documented

### ISSUE THREAD

**Issue by erikerlandson** [cibotech/evilplot#86]
For example, `FunctionPlot` no longer seems to pass its label information up to `Overlay`'s legend generation:
https://cibotech.github.io/evilplot/plot-catalog.html#function-plot

**Comment by johndavidhahn** [comment]
Yep, looks like some changes in the 0.6. line broke that.  Specifically, what I've found so far is that plots using the new `CartesianPlot`, or renderers built on `CompoundPlotRenderer` are loosing legend information coming from its renderers (such as plots with series).  

I'm still trying to determine the impact of this, initial analysis looks like its might be limited to `FunctionPlot` and possibly the newer `BinnedPlot` (new variation on Histogram).

We are working on it, but may take a bit to fully resolve.

**Comment by erikerlandson** [comment]
Thank you @johndavidhahn !

**Comment by chrisshafer** [comment]
Ill take responsibility for this. Apologies! This should fix the issue https://github.com/cibotech/evilplot/pull/87

**Comment by johndavidhahn** [comment]
Fix deployed in 0.6.3
